### ISSUE TITLE
funeralzone/valueobjects 0.4.5 Requirement: Requires PHP >= 7.1, but my php version (8.0.1)

### ISSUE THREAD

**Issue by mechadragon01** [funeralzone/valueobjects#14]
funeralzone/valueobjects 0.4.5 requires php ^7.1.0 -> your php version (8.0.1) does not satisfy that requirement.

On Requirements: Requires PHP >= 7.1, shouldn't it be =7.1
PHP version 8.0.1 is >= 7.1, but doesn't work

**Comment by chrisharrison** [comment]
^7.1.0 is correct because that means any major version 7. PHP 8 does not guarantee backwards compatibility with 7.

We can't do anything about previous releases, but if you use the latest version (`0.5`) that is PHP 8 compatible.
